---
name: KOTH
author: JaxkDev
version: 1.0.0
api: 4.0.0
main: JaxkDev\KOTH\Main
src-namespace-prefix: JaxkDev\KOTH
website: "https://github.com/JaxkDev/KOTH"
description: "King of The Hill, A mini-game plugin by JaxkDev"

extensions: [sqlite3]

commands:
  koth:
    description: "KOTH general command"
    permission: koth.command
    usage: /koth help
    permission-message: "You do not have permission to use this command."

permissions:
  koth.command:
    description: "Allows player to use /koth"
    default: true
  koth.command.delete:
    description: "Allows player to delete an arena."
    default: op
  koth.command.create:
    description: "Allows player to create and setup an arena."
    default: op
  koth.command.enable:
    description: "Allows player to enable an arena."
    default: op
  koth.command.disable:
    description: "Allows player to disable an arena."
    default: op
  koth.command.rewards:
    description: "Allows player to modify the reward of an arena."
    default: op
  koth.command.info:
    description: "Allows player to see more details about an arena."
    default: true
  koth.command.list:
    description: "Allows player to see the Arena's and their current status."
    default: true
  koth.command.join:
    description: "Allows player to join a game."
    default: true
  koth.command.leave:
    description: "Allows player to chicken out of a game."
    default: true
  koth.command.start:
    description: "Allows player to start an arena."
    default: true
  koth.command.forcestart:
    description: "Allows player to force start an arena."
    default: op
...
